repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.49.0
    hooks:
      - id: markdownlint
        args:
          [
            "--config",
            ".markdownlint.json",
            "--fix",
          ]
        pass_filenames: true
        types: [file, markdown, non-executable]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.15.20"
    hooks:
      - id: ruff
        args:
          - --fix
          - --target-version=py312
      - id: ruff-format
        args:
          - --line-length=88
          - --target-version=py312

  - repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
      - id: isort
        args:
          - --filter-files

# Specific configuration for https://pre-commit.ci
ci:
  autofix_commit_msg: "[pre-commit.ci] Automatic updates applied by git hooks."
  autofix_prs: true
  autoupdate_commit_msg: "[pre-commit.ci] Automatic updates applied by git hooks."
  autoupdate_schedule: weekly
  skip: []
  submodules: false
