name: 🚀 Release

on:
  push:
    tags:
      - '*'

jobs:

  release:

    name: 👷 GitHub Release
    runs-on: ubuntu-latest

    if: github.ref_type == 'tag'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install qt tools dependencies
        run: |
          sudo apt update
          sudo apt install -y qt6-base-dev qt6-tools-dev-tools
          echo "/usr/lib/qt6/bin" >> "$GITHUB_PATH"

      - name: Compile translations
        run: lrelease {{ cookiecutter.plugin_name_slug }}/*.ts

      - name: Zip the QField plugin
        run: |
          cd {{ cookiecutter.plugin_name_slug }}
          zip -r "../{{ cookiecutter.plugin_name_slug }}-${{ github.ref_name }}.zip" ./*
          zip -r "../{{ cookiecutter.plugin_name_slug }}-latest.zip" ./*

      - name: Generate QR code
        run: |
          pip install qrcode[pil] --quiet
          python3 ./scripts/generate_qr_code.py
        env:
          FILE_URL: https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/{{ cookiecutter.plugin_name_slug }}-${{ github.ref_name }}.zip

      - name: Create GitHub Release with assets
        uses: softprops/action-gh-release@v3
        with:
          generate_release_notes: true
          files: |
            {{ cookiecutter.plugin_name_slug }}-${{ github.ref_name }}.zip
            {{ cookiecutter.plugin_name_slug }}-latest.zip
            qrcode.png
          body: |
            Flash the following QR code in QField to run this plugin version:

            <img src="https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/qrcode.png" alt="QR Code" width="360"/>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
