name: 🎳 Tests

on:
  push:
    branches:
      - main
    paths:
      - "{{ cookiecutter.plugin_name_slug }}/main.qml"
      - "tests/**"
      - ".github/workflows/tests.yml"
  pull_request:
    branches:
      - main
    paths:
      - "{{ cookiecutter.plugin_name_slug }}/main.qml"
      - "tests/**"
      - ".github/workflows/tests.yml"

jobs:
  tests:

    name: 🤞 Run QField plugin unit tests
    runs-on: ubuntu-latest

    container:
      image: qgis/qgis:{% raw %}${{ matrix.qgis-image-tag }}{% endraw %}
    strategy:
      matrix:
        qgis-image-tag:
          # list the accurate QGIS image tags to test against
          # see: https://hub.docker.com/r/qgis/qgis/tags
          - "4.0-questing"
        qfield-refs:
          # list the QField branches to test against
          - release-4_2
          - master
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Checkout QField repository
        uses: actions/checkout@v6
        with:
          repository: opengisch/QField
          path: QField
          ref: "{% raw %}${{ matrix.qfield-refs }}{% endraw %}"

      - name: Install PyQt6 system dependencies
        run: apt install -y qt6-websockets-dev qml6-module-qtcore qml6-module-qtmultimedia python3-pyqt6.qtqml python3-pyqt6.qtquick python3-pyqt6.qtmultimedia

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Create venv with system site packages
        run: uv venv --system-site-packages

      - name: Add QGIS Python path
        run: |
          SITE_PACKAGES=$(uv run python -c "import site; print(site.getsitepackages()[0])")
          echo "/usr/share/qgis/python" > "$SITE_PACKAGES/qgis.pth"

      - name: Install dependencies
        run: uv sync

      - name: Run unit tests with pytest
        env:
          QGIS_IN_CI: 1
        run: xvfb-run uv run pytest tests -v --qgis_disable_gui
